spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/seventest}
    username: ${SPRING_DATASOURCE_USERNAME:seventest_user}
    password: ${SPRING_DATASOURCE_PASSWORD:seventest_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
